import type { Boat } from "./types";

export const FEATURED_BOATS: Boat[] = [
  {
    id: "sun-odyssey-440",
    name: "Sun Odyssey 440 — Bercy",
    location: "Marseille, Vieux-Port",
    type: "voilier",
    rating: 4.9,
    reviewCount: 47,
    pricePerDay: 890,
    imageUrl: "",
    imageSeed: "sun-odyssey",
    badge: { label: "Coup de cœur", variant: "red", icon: "fa-heart" },
    cabins: 5,
    toilets: 3,
    year: 2023,
    capacity: 8,
    length: "13,5 m",
    width: "4,35 m",
    speed: "9 nœuds",
    fuel: "Diesel",
    license: "Requis",
  },
  {
    id: "bavaria-46-cruiser",
    name: "Bavaria 46 Cruiser",
    location: "Nice, Port de la Darse",
    type: "voilier",
    rating: 4.7,
    reviewCount: 32,
    pricePerDay: 860,
    imageUrl: "",
    imageSeed: "bavaria-cruiser",
    badge: { label: "Voilier", variant: "default" },
    cabins: 4,
    toilets: 2,
    year: 2022,
    capacity: 6,
    length: "14,1 m",
    width: "4,48 m",
    speed: "8 nœuds",
    fuel: "Diesel",
    license: "Requis",
  },
  {
    id: "jeanneau-54-ds",
    name: "Jeanneau 54 DS",
    location: "Marseille, La Ciotat",
    type: "voilier",
    rating: 4.5,
    reviewCount: 18,
    pricePerDay: 1240,
    imageUrl: "",
    imageSeed: "jeanneau-54",
    badge: { label: "Nouveau", variant: "green" },
    cabins: 5,
    toilets: 3,
    year: 2023,
    capacity: 10,
    length: "16,7 m",
    width: "4,96 m",
    speed: "10 nœuds",
    fuel: "Diesel",
    license: "Requis",
  },
];

export const ALL_BOATS: Boat[] = [
  ...FEATURED_BOATS,
  {
    id: "beneteau-oceanis-511",
    name: "Bénéteau Oceanis 511",
    location: "La Seyne-sur-Mer",
    type: "voilier",
    rating: 4.6,
    reviewCount: 29,
    pricePerDay: 720,
    imageUrl: "",
    imageSeed: "boat-sea4",
    cabins: 3,
    toilets: 2,
    year: 2021,
    capacity: 6,
  },
  {
    id: "dufour-430",
    name: "Dufour 430",
    location: "Cassis, Port Miou",
    type: "sans-permis",
    rating: 4.3,
    reviewCount: 12,
    pricePerDay: 480,
    imageUrl: "",
    imageSeed: "boat-sail5",
    badge: { label: "Sans permis", variant: "default" },
    cabins: 3,
    toilets: 1,
    year: 2020,
    capacity: 5,
  },
  {
    id: "leopard-45",
    name: "Leopard 45 Catamaran",
    location: "Cannes, Vieux-Port",
    type: "catamaran",
    rating: 4.8,
    reviewCount: 51,
    pricePerDay: 1650,
    imageUrl: "",
    imageSeed: "catamaran6",
    badge: { label: "Coup de cœur", variant: "red", icon: "fa-heart" },
    cabins: 4,
    toilets: 4,
    year: 2022,
    capacity: 8,
  },
  {
    id: "hanse-508",
    name: "Hanse 508",
    location: "Ajaccio, Corse",
    type: "voilier",
    rating: 4.5,
    reviewCount: 23,
    pricePerDay: 980,
    imageUrl: "",
    imageSeed: "boat-harbor7",
    cabins: 5,
    toilets: 3,
    year: 2021,
    capacity: 9,
  },
  {
    id: "fountaine-pajot-47",
    name: "Fountaine Pajot 47",
    location: "Marseille, Vieux-Port",
    type: "catamaran",
    rating: 4.6,
    reviewCount: 8,
    pricePerDay: 890,
    imageUrl: "",
    imageSeed: "fountain-pajot",
    badge: { label: "Nouveau", variant: "green" },
    cabins: 4,
    toilets: 4,
    year: 2023,
    capacity: 8,
  },
];
