import type { Boat } from "./types";

export const FEATURED_BOATS: Boat[] = [
  {
    id: "sun-odyssey-440",
    name: "Sun Odyssey 440 — Bercy",
    location: "Marseille, Vieux-Port",
    coordinates: { lat: 43.2951, lng: 5.3739 },
    type: "voilier",
    rating: 4.9,
    reviewCount: 47,
    pricePerDay: 890,
    imageUrl: "",
    imageSeed: "sun-odyssey",
    imageQuery: "sailboat,yacht,mediterranean",
    owner: { name: "Marc D.", avatarSeed: "marc-owner" },
    badge: { label: "Coup de cœur", variant: "red", icon: "fa-heart" },
    cabins: 5,
    toilets: 3,
    year: 2023,
    capacity: 8,
    length: "13,5 m",
    width: "4,35 m",
    speed: "9 nœuds",
    fuel: "Diesel",
    license: "Requis",
  },
  {
    id: "bavaria-46-cruiser",
    name: "Bavaria 46 Cruiser",
    location: "Nice, Port de la Darse",
    coordinates: { lat: 43.7042, lng: 7.3103 },
    type: "voilier",
    rating: 4.7,
    reviewCount: 32,
    pricePerDay: 860,
    imageUrl: "",
    imageSeed: "bavaria-cruiser",
    imageQuery: "sailboat,cruiser,sailing",
    owner: { name: "Claire B.", avatarSeed: "claire-owner" },
    badge: { label: "Voilier", variant: "default" },
    cabins: 4,
    toilets: 2,
    year: 2022,
    capacity: 6,
    length: "14,1 m",
    width: "4,48 m",
    speed: "8 nœuds",
    fuel: "Diesel",
    license: "Requis",
  },
  {
    id: "jeanneau-54-ds",
    name: "Jeanneau 54 DS",
    location: "Marseille, La Ciotat",
    coordinates: { lat: 43.1747, lng: 5.6053 },
    type: "voilier",
    rating: 4.5,
    reviewCount: 18,
    pricePerDay: 1240,
    imageUrl: "",
    imageSeed: "jeanneau-54",
    imageQuery: "sailboat,yacht,luxury",
    owner: { name: "Julien P.", avatarSeed: "julien-owner" },
    badge: { label: "Nouveau", variant: "green" },
    cabins: 5,
    toilets: 3,
    year: 2023,
    capacity: 10,
    length: "16,7 m",
    width: "4,96 m",
    speed: "10 nœuds",
    fuel: "Diesel",
    license: "Requis",
  },
];

export const ALL_BOATS: Boat[] = [
  ...FEATURED_BOATS,
  {
    id: "beneteau-oceanis-511",
    name: "Bénéteau Oceanis 511",
    location: "La Seyne-sur-Mer",
    coordinates: { lat: 43.1003, lng: 5.8836 },
    type: "voilier",
    rating: 4.6,
    reviewCount: 29,
    pricePerDay: 720,
    imageUrl: "",
    imageSeed: "boat-sea4",
    imageQuery: "sailboat,ocean",
    owner: { name: "Sophie L.", avatarSeed: "sophie-owner" },
    cabins: 3,
    toilets: 2,
    year: 2021,
    capacity: 6,
  },
  {
    id: "dufour-430",
    name: "Dufour 430",
    location: "Cassis, Port Miou",
    coordinates: { lat: 43.2148, lng: 5.5386 },
    type: "sans-permis",
    rating: 4.3,
    reviewCount: 12,
    pricePerDay: 480,
    imageUrl: "",
    imageSeed: "boat-sail5",
    imageQuery: "sailboat,coast",
    owner: { name: "Nicolas R.", avatarSeed: "nicolas-owner" },
    badge: { label: "Sans permis", variant: "default" },
    cabins: 3,
    toilets: 1,
    year: 2020,
    capacity: 5,
  },
  {
    id: "leopard-45",
    name: "Leopard 45 Catamaran",
    location: "Cannes, Vieux-Port",
    coordinates: { lat: 43.5513, lng: 7.0128 },
    type: "catamaran",
    rating: 4.8,
    reviewCount: 51,
    pricePerDay: 1650,
    imageUrl: "",
    imageSeed: "catamaran6",
    imageQuery: "catamaran,sailing,yacht",
    owner: { name: "Émilie T.", avatarSeed: "emilie-owner" },
    badge: { label: "Coup de cœur", variant: "red", icon: "fa-heart" },
    cabins: 4,
    toilets: 4,
    year: 2022,
    capacity: 8,
  },
  {
    id: "hanse-508",
    name: "Hanse 508",
    location: "Ajaccio, Corse",
    coordinates: { lat: 41.9192, lng: 8.7386 },
    type: "voilier",
    rating: 4.5,
    reviewCount: 23,
    pricePerDay: 980,
    imageUrl: "",
    imageSeed: "boat-harbor7",
    imageQuery: "sailboat,harbor,sailing",
    owner: { name: "Antoine M.", avatarSeed: "antoine-owner" },
    cabins: 5,
    toilets: 3,
    year: 2021,
    capacity: 9,
  },
  {
    id: "fountaine-pajot-47",
    name: "Fountaine Pajot 47",
    location: "Marseille, Vieux-Port",
    coordinates: { lat: 43.2965, lng: 5.3712 },
    type: "catamaran",
    rating: 4.6,
    reviewCount: 8,
    pricePerDay: 890,
    imageUrl: "",
    imageSeed: "fountain-pajot",
    imageQuery: "catamaran,yacht",
    owner: { name: "Laura G.", avatarSeed: "laura-owner" },
    badge: { label: "Nouveau", variant: "green" },
    cabins: 4,
    toilets: 4,
    year: 2023,
    capacity: 8,
  },
  {
    id: "cap-camarat-6-5",
    name: "Jeanneau Cap Camarat 6.5",
    location: "Antibes, Port Vauban",
    coordinates: { lat: 43.5809, lng: 7.1251 },
    type: "moteur",
    rating: 4.3,
    reviewCount: 17,
    pricePerDay: 180,
    imageUrl: "",
    imageSeed: "motorboat-small1",
    imageQuery: "motorboat,speedboat",
    owner: { name: "Thomas V.", avatarSeed: "thomas-owner" },
    badge: { label: "Bateau à moteur", variant: "default" },
    year: 2021,
    capacity: 2,
    license: "Requis",
  },
  {
    id: "beneteau-flyer-8",
    name: "Bénéteau Flyer 8 SUNdeck",
    location: "Cannes, Port Pierre Canto",
    coordinates: { lat: 43.5445, lng: 7.0396 },
    type: "moteur",
    rating: 4.4,
    reviewCount: 15,
    pricePerDay: 380,
    imageUrl: "",
    imageSeed: "motorboat-flyer2",
    imageQuery: "motorboat,yacht",
    owner: { name: "Camille F.", avatarSeed: "camille-owner" },
    cabins: 1,
    toilets: 1,
    year: 2022,
    capacity: 6,
  },
  {
    id: "azimut-55-fly",
    name: "Azimut 55 Fly",
    location: "Saint-Tropez, Vieux-Port",
    coordinates: { lat: 43.2727, lng: 6.6407 },
    type: "moteur",
    rating: 4.9,
    reviewCount: 41,
    pricePerDay: 2200,
    imageUrl: "",
    imageSeed: "motoryacht-luxe3",
    imageQuery: "motoryacht,luxury,yacht",
    owner: { name: "Alexandre K.", avatarSeed: "alexandre-owner" },
    badge: { label: "Luxe", variant: "red", icon: "fa-crown" },
    cabins: 4,
    toilets: 3,
    year: 2023,
    capacity: 12,
  },
  {
    id: "sunfast-330-budget",
    name: "Jeanneau Sun Fast 330",
    location: "Toulon, Port Saint-Louis",
    coordinates: { lat: 43.1178, lng: 5.9282 },
    type: "voilier",
    rating: 4.2,
    reviewCount: 11,
    pricePerDay: 390,
    imageUrl: "",
    imageSeed: "sailboat-budget4",
    imageQuery: "sailboat,regatta",
    owner: { name: "Manon S.", avatarSeed: "manon-owner" },
    cabins: 2,
    toilets: 1,
    year: 2018,
    capacity: 4,
  },
  {
    id: "nautitech-open-46",
    name: "Nautitech Open 46",
    location: "Hyères, Port Saint-Pierre",
    coordinates: { lat: 43.0958, lng: 6.1280 },
    type: "catamaran",
    rating: 4.4,
    reviewCount: 14,
    pricePerDay: 650,
    imageUrl: "",
    imageSeed: "catamaran-open5",
    imageQuery: "catamaran,ocean",
    owner: { name: "Hugo D.", avatarSeed: "hugo-owner" },
    cabins: 3,
    toilets: 2,
    year: 2020,
    capacity: 6,
  },
  {
    id: "quicksilver-sans-permis",
    name: "Quicksilver Activ 605",
    location: "Antibes, Port du Croûton",
    coordinates: { lat: 43.5606, lng: 7.1197 },
    type: "sans-permis",
    rating: 4.5,
    reviewCount: 22,
    pricePerDay: 540,
    imageUrl: "",
    imageSeed: "no-license-boat6",
    imageQuery: "motorboat,dayboat",
    owner: { name: "Chloé N.", avatarSeed: "chloe-owner" },
    badge: { label: "Sans permis", variant: "default" },
    cabins: 2,
    toilets: 1,
    year: 2022,
    capacity: 4,
    license: "Non requis",
  },
  {
    id: "penichette-nicols",
    name: "Penichette Nicols 1160",
    location: "Béziers, Canal du Midi",
    coordinates: { lat: 43.3415, lng: 3.2160 },
    type: "habitable",
    rating: 4.3,
    reviewCount: 19,
    pricePerDay: 320,
    imageUrl: "",
    imageSeed: "houseboat-canal7",
    imageQuery: "houseboat,canal",
    owner: { name: "Pierre A.", avatarSeed: "pierre-owner" },
    badge: { label: "Sans permis", variant: "default" },
    cabins: 2,
    toilets: 1,
    year: 2019,
    capacity: 8,
    license: "Non requis",
  },
  {
    id: "habitable-bonifacio",
    name: "Trawler Grand Large 52",
    location: "Bonifacio, Corse",
    coordinates: { lat: 41.3888, lng: 9.1595 },
    type: "habitable",
    rating: 4.7,
    reviewCount: 27,
    pricePerDay: 1450,
    imageUrl: "",
    imageSeed: "trawler-corse8",
    imageQuery: "trawler,yacht",
    owner: { name: "Isabelle C.", avatarSeed: "isabelle-owner" },
    badge: { label: "Coup de cœur", variant: "red", icon: "fa-heart" },
    cabins: 5,
    toilets: 3,
    year: 2023,
    capacity: 10,
  },
  {
    id: "zodiac-medline-elite",
    name: "Zodiac Medline Elite",
    location: "Golfe de Saint-Tropez",
    coordinates: { lat: 43.2500, lng: 6.6400 },
    type: "semi-rigide",
    rating: 4.1,
    reviewCount: 9,
    pricePerDay: 210,
    imageUrl: "",
    imageSeed: "semi-rigide-zod9",
    imageQuery: "rib,dinghy,boat",
    owner: { name: "Maxime B.", avatarSeed: "maxime-owner" },
    year: 2021,
    capacity: 10,
  },
  {
    id: "ponton-lagoon-grimaud",
    name: "Ponton Lagoon Grimaud",
    location: "Port Grimaud",
    coordinates: { lat: 43.2726, lng: 6.5794 },
    type: "ponton",
    rating: 4.0,
    reviewCount: 6,
    pricePerDay: 260,
    imageUrl: "",
    imageSeed: "pontoon-grimaud10",
    imageQuery: "pontoon,boat",
    owner: { name: "Léa H.", avatarSeed: "lea-owner" },
    year: 2020,
    capacity: 12,
  },
];
