import type { FullDestination } from "@/shared/types";

export const ALL_DESTINATIONS: FullDestination[] = [
  {
    slug: "cote-azur",
    name: "Côte d'Azur",
    country: "France",
    flag: "FR",
    region: "Méditerranée française",
    tagline: "Le joyau bleu de la Méditerranée",
    description:
      "De Nice à Menton en passant par Cannes et Monaco, la Côte d'Azur est l'une des destinations de voile les plus réputées au monde. Ses eaux cristallines, ses criques secrètes et ses ports de prestige en font un terrain de jeu idéal pour tous les plaisanciers.",
    boatCount: 312,
    imageSeed: "cote-azur",
    heroSeed: "azur-hero",
    heroImage: "/images/destinations/cote-azur/pexels-willian-justen-17506365.jpg",
    bestPeriod: "Juin à Septembre",
    avgTemp: "26°C",
    avgWind: "Force 3-4",
    priceFrom: 290,
    activities: ["Snorkeling", "Plongée", "Water-ski", "Pêche", "Wakeboard", "Paddle", "Jet-ski"],
    highlights: [
      { title: "Calanques de Cassis", desc: "Fjords méditerranéens aux eaux turquoise, accessibles uniquement par la mer.", icon: "fa-water", image: "/images/destinations/cote-azur/calanques-cassis.jpg" },
      { title: "Îles de Lérins", desc: "Deux îles préservées face à Cannes, paradis de biodiversité marine.", icon: "fa-umbrella-beach", image: "/images/destinations/cote-azur/iles-de-lerins.jpg" },
      { title: "Monaco & Menton", desc: "Naviguez entre glamour et charme provençal le long de la frontière italienne.", icon: "fa-crown", image: "/images/destinations/cote-azur/monaco.jpg" },
      { title: "Saint-Tropez", desc: "Le mythe de la Riviera, entre vieilles pierres et yachts de rêve.", icon: "fa-star", image: "/images/destinations/cote-azur/saint-tropez.jpg" },
    ],
    tags: ["Luxe", "Famille", "Plage", "Culture", "Gastronomie"],
    gallerySeeds: ["azur1", "azur2", "azur3", "azur4"],
    galleryImages: [
      "/images/destinations/cote-azur/nice-aerienne.jpg",
      "/images/destinations/cote-azur/villefranche-sur-mer.jpg",
      "/images/destinations/cote-azur/cannes.png",
      "/images/destinations/cote-azur/menton.jpg",
    ],
    center: { lat: 43.53, lng: 7.05 },
  },
  {
    slug: "corse",
    name: "Corse",
    country: "France",
    flag: "FR",
    region: "Méditerranée — Île de Beauté",
    tagline: "L'île sauvage aux mille couleurs",
    description:
      "La Corse s'impose comme l'une des plus belles destinations de voile de Méditerranée. Ses 1 000 km de côtes découpées, ses eaux émeraude et ses criques inaccessibles à pied en font une expérience de navigation unique. Nature préservée classée UNESCO, villages perchés et gastronomie généreuse.",
    boatCount: 224,
    imageSeed: "corse-plage",
    heroSeed: "corse-hero",
    heroImage: "/images/destinations/corse/pexels-slimmars-13-197677686-38525042.jpg",
    bestPeriod: "Mai à Septembre",
    avgTemp: "24°C",
    avgWind: "Force 3-5",
    priceFrom: 250,
    activities: ["Randonnée nautique", "Plongée", "Kayak", "Pêche", "Snorkeling", "Canyoning"],
    highlights: [
      { title: "Golfe de Porto", desc: "Site UNESCO aux falaises de granit rouge plongeant dans une mer turquoise.", icon: "fa-mountain", image: "/images/destinations/corse/golfe-de-porto.jpg" },
      { title: "Réserve de Scandola", desc: "Réserve naturelle protégée, accessible uniquement par la mer.", icon: "fa-leaf", image: "/images/destinations/corse/scandola.jpg" },
      { title: "Bonifacio", desc: "Cité médiévale perchée sur des falaises calcaires blanches à couper le souffle.", icon: "fa-city", image: "/images/destinations/corse/bonifacio.jpg" },
      { title: "Désert des Agriates", desc: "Plages sauvages désertes aux eaux dignes des Caraïbes.", icon: "fa-umbrella-beach", image: "/images/destinations/corse/desert-agriates.jpg" },
    ],
    tags: ["Nature", "Aventure", "Plage", "Culture", "Déconnexion"],
    gallerySeeds: ["corse1", "corse2", "corse3", "corse4"],
    galleryImages: [
      "/images/destinations/corse/pexels-arnaud-38670021.jpg",
      "/images/destinations/corse/pexels-slimmars-13-197677686-38434441.jpg",
      "/images/destinations/corse/pexels-mermoz-lionel-622163994-18035844.jpg",
      "/images/destinations/corse/pexels-arnaud-38669979.jpg",
      "/images/destinations/corse/pexels-slimmars-13-197677686-38525043.jpg",
    ],
    center: { lat: 42.15, lng: 9.05 },
  },
  {
    slug: "bretagne",
    name: "Bretagne",
    country: "France",
    flag: "FR",
    region: "Atlantique — France",
    tagline: "La mer à l'état brut",
    description:
      "La Bretagne offre une expérience de navigation radicalement différente : côtes découpées, phares légendaires, marées spectaculaires, ambiance sauvage et gastronomie de caractère. Pour les navigateurs qui cherchent l'aventure et l'authenticité plutôt que le soleil méditerranéen.",
    boatCount: 178,
    imageSeed: "bretagne-mer",
    heroSeed: "bretagne-hero",
    heroImage: "/images/destinations/bretagne/pexels-ishaq-ali-anis-2149874681-31207526.jpg",
    bestPeriod: "Juin à Août",
    avgTemp: "18°C",
    avgWind: "Force 4-6",
    priceFrom: 130,
    activities: ["Voile sportive", "Surf", "Pêche", "Randonnée côtière", "Observation de cétacés", "Planche à voile"],
    highlights: [
      { title: "Golfe du Morbihan", desc: "Mer intérieure mystérieuse aux 40 îles, marées et courants fascinants.", icon: "fa-water", image: "/images/destinations/bretagne/pexels-jan-van-der-wolf-11680885-20182858.jpg" },
      { title: "Archipel des Glénan", desc: "Lagon aux eaux turquoise inattendu, bijou caché de l'Atlantique.", icon: "fa-gem", image: "/images/destinations/bretagne/pexels-gilles-33538200.jpg" },
      { title: "Belle-Île-en-Mer", desc: "La plus grande île bretonne, côte sauvage et village de Locmaria.", icon: "fa-umbrella-beach", image: "/images/destinations/bretagne/pexels-philippe-serrand-337910945-17891904.jpg" },
      { title: "Pointe du Raz", desc: "L'un des caps les plus spectaculaires d'Europe, face à l'Atlantique.", icon: "fa-wind", image: "/images/destinations/bretagne/pexels-gilles-33552107.jpg" },
    ],
    tags: ["Aventure", "Nature", "Voile sportive", "Authenticité", "Gastronomie"],
    gallerySeeds: ["bretagne1", "bretagne2", "bretagne3", "bretagne4"],
    galleryImages: [
      "/images/destinations/bretagne/pexels-jan-van-der-wolf-11680885-20182858.jpg",
      "/images/destinations/bretagne/pexels-gilles-33538200.jpg",
      "/images/destinations/bretagne/pexels-philippe-serrand-337910945-17891904.jpg",
      "/images/destinations/bretagne/pexels-slimmars-13-197677686-34681436.jpg",
      "/images/destinations/bretagne/pexels-philippe-serrand-337910945-18382376.jpg",
    ],
    center: { lat: 47.6, lng: -3.0 },
  },
  {
    slug: "la-rochelle",
    name: "La Rochelle",
    country: "France",
    flag: "FR",
    region: "Atlantique — Charente-Maritime",
    tagline: "La capitale française de la voile",
    description:
      "La Rochelle est le cœur battant de la voile atlantique française. Ses tours médiévales, son Vieux-Port animé et sa façade ouverte sur l'Atlantique en font un point de départ exceptionnel. À quelques encablures : l'Île de Ré aux villages blancs et l'Île d'Oléron, paradis de la nature et des parcs à huîtres.",
    boatCount: 45,
    imageSeed: "la-rochelle-voile",
    heroSeed: "la-rochelle-atlantic",
    heroImage: "/images/destinations/la-rochelle/pexels-pablo-32821994.jpg",
    bestPeriod: "Juin à Septembre",
    avgTemp: "20°C",
    avgWind: "Force 3-5",
    priceFrom: 150,
    activities: ["Voile", "Pêche", "Kayak de mer", "Kitesurf", "Randonnée côtière", "Planche à voile"],
    highlights: [
      { title: "Vieux-Port de La Rochelle", desc: "L'un des plus beaux ports médiévaux d'Europe, gardé par ses trois tours emblématiques.", icon: "fa-anchor", image: "/images/destinations/la-rochelle/vieux-port.jpg" },
      { title: "Île de Ré", desc: "Vélos, marais salants, villages blancs aux volets verts et plages de sable fin.", icon: "fa-umbrella-beach", image: "/images/destinations/la-rochelle/ile-de-re.jpg" },
      { title: "Île d'Oléron", desc: "La plus grande île française après la Corse, entre pinèdes, parcs à huîtres et plages sauvages.", icon: "fa-fish", image: "/images/destinations/la-rochelle/ile-oleron.jpg" },
      { title: "Marais Poitevin", desc: "La Venise Verte, mosaïque de canaux, de prairies et de forêts inondées au fil de l'eau.", icon: "fa-leaf", image: "/images/destinations/la-rochelle/marais-poitevin.jpg" },
    ],
    tags: ["Voile", "Nature", "Famille", "Histoire", "Gastronomie"],
    gallerySeeds: ["larochelle1", "larochelle2", "larochelle3", "larochelle4"],
    center: { lat: 46.16, lng: -1.15 },
  },
  {
    slug: "languedoc",
    name: "Languedoc",
    country: "France",
    flag: "FR",
    region: "Méditerranée — Occitanie",
    tagline: "La Méditerranée authentique et accessible",
    description:
      "Le Languedoc dévoile une Méditerranée moins connue mais tout aussi envoûtante : les canaux de Sète surnommée « la Singulière », les plages d'Agde bâties en basalte volcanique noir, la lagune de Thau et ses parcs à huîtres, sans oublier les marinas modernes de La Grande Motte. Une navigation savoureuse, à l'image de sa gastronomie.",
    boatCount: 60,
    imageSeed: "sete-languedoc",
    heroSeed: "sete-port-languedoc",
    heroImage: "/images/destinations/languedoc/pexels-slimmars-13-197677686-31682903.jpg",
    bestPeriod: "Mai à Octobre",
    avgTemp: "24°C",
    avgWind: "Force 3-4",
    priceFrom: 120,
    activities: ["Voile", "Plongée", "Kayak", "Pêche", "Snorkeling", "Dégustation d'huîtres", "Joutes nautiques"],
    highlights: [
      { title: "Sète, la Singulière", desc: "Port de pêche et canal incontournable, la « Venise du Languedoc » au cœur de l'étang de Thau.", icon: "fa-water", image: "/images/destinations/languedoc/sete.jpg" },
      { title: "Cap d'Agde & Agde noir", desc: "Ancienne cité grecque aux maisons en basalte volcanique unique, avec une marina de premier rang.", icon: "fa-city", image: "/images/destinations/languedoc/cap-agde.jpg" },
      { title: "Étang de Thau", desc: "Lagune méditerranéenne réputée pour ses huîtres et moules, un écrin naturel préservé.", icon: "fa-fish", image: "/images/destinations/languedoc/etang-thau.jpg" },
      { title: "La Grande Motte", desc: "Station balnéaire iconique aux pyramides blanches, port de plaisance moderne de référence.", icon: "fa-umbrella-beach", image: "/images/destinations/languedoc/grande-motte.jpg" },
    ],
    tags: ["Authenticité", "Gastronomie", "Famille", "Nature", "Culture"],
    gallerySeeds: ["languedoc1", "languedoc2", "languedoc3", "languedoc4"],
    center: { lat: 43.41, lng: 3.70 },
  },
  {
    slug: "camargue",
    name: "Camargue",
    country: "France",
    flag: "FR",
    region: "Méditerranée — Provence",
    tagline: "Le delta sauvage au bout de la Méditerranée",
    description:
      "La Camargue est l'une des plus grandes zones humides d'Europe, classée réserve de biosphère par l'UNESCO. Depuis Port-Camargue — l'une des plus grandes marinas d'Europe — naviguez vers des plages vierges désertes, observez les flamants roses en vol et ancrez-vous face aux remparts médiévaux d'Aigues-Mortes.",
    boatCount: 35,
    imageSeed: "camargue-delta",
    heroSeed: "camargue-port-sailing",
    heroImage: "/images/destinations/camargue/pexels-slimmars-13-197677686-31682591.jpg",
    bestPeriod: "Avril à Octobre",
    avgTemp: "22°C",
    avgWind: "Force 3-5 (mistral possible)",
    priceFrom: 110,
    activities: ["Voile", "Observation des oiseaux", "Paddle", "Pêche", "Randonnée équestre", "Baignade"],
    highlights: [
      { title: "Port-Camargue", desc: "L'une des plus grandes marinas d'Europe (4 500 anneaux) au cœur du delta du Rhône.", icon: "fa-anchor", image: "/images/destinations/camargue/port-camargue.jpg" },
      { title: "Flamants roses & faune sauvage", desc: "Flamants, chevaux camarguais et taureaux évoluent librement dans la réserve naturelle.", icon: "fa-dove", image: "/images/destinations/camargue/flamants-roses.jpg" },
      { title: "Aigues-Mortes médiéval", desc: "Cité fortifiée du XIIIe siècle au cœur des salins, sur les traces des croisades de Saint Louis.", icon: "fa-chess-rook", image: "/images/destinations/camargue/aigues-mortes.jpg" },
      { title: "Plages sauvages désertes", desc: "Des kilomètres de plages vierges accessibles uniquement par la mer, hors des sentiers battus.", icon: "fa-umbrella-beach", image: "/images/destinations/camargue/plages-sauvages.jpg" },
    ],
    tags: ["Nature", "Aventure", "Déconnexion", "Culture", "Famille"],
    gallerySeeds: ["camargue1", "camargue2", "camargue3", "camargue4"],
    center: { lat: 43.52, lng: 4.13 },
  },
];
