import type { FullDestination } from "@/shared/types";

export const ALL_DESTINATIONS: FullDestination[] = [
  {
    slug: "cote-azur",
    name: "Côte d'Azur",
    country: "France",
    flag: "FR",
    region: "Méditerranée française",
    tagline: "Le joyau bleu de la Méditerranée",
    description:
      "De Nice à Menton en passant par Cannes et Monaco, la Côte d'Azur est l'une des destinations de voile les plus réputées au monde. Ses eaux cristallines, ses criques secrètes et ses ports de prestige en font un terrain de jeu idéal pour tous les plaisanciers.",
    boatCount: 312,
    imageSeed: "cote-azur",
    heroSeed: "azur-hero",
    heroImage: "/images/destinations/cote-azur/nice-aerienne.jpg",
    bestPeriod: "Juin à Septembre",
    avgTemp: "26°C",
    avgWind: "Force 3-4",
    priceFrom: 290,
    activities: ["Snorkeling", "Plongée", "Water-ski", "Pêche", "Wakeboard", "Paddle", "Jet-ski"],
    highlights: [
      { title: "Calanques de Cassis", desc: "Fjords méditerranéens aux eaux turquoise, accessibles uniquement par la mer.", icon: "fa-water", image: "/images/destinations/cote-azur/calanques-cassis.jpg" },
      { title: "Îles de Lérins", desc: "Deux îles préservées face à Cannes, paradis de biodiversité marine.", icon: "fa-umbrella-beach", image: "/images/destinations/cote-azur/iles-de-lerins.jpg" },
      { title: "Monaco & Menton", desc: "Naviguez entre glamour et charme provençal le long de la frontière italienne.", icon: "fa-crown", image: "/images/destinations/cote-azur/monaco.jpg" },
      { title: "Saint-Tropez", desc: "Le mythe de la Riviera, entre vieilles pierres et yachts de rêve.", icon: "fa-star", image: "/images/destinations/cote-azur/saint-tropez.jpg" },
    ],
    tags: ["Luxe", "Famille", "Plage", "Culture", "Gastronomie"],
    gallerySeeds: ["azur1", "azur2", "azur3", "azur4"],
    galleryImages: [
      "/images/destinations/cote-azur/nice-aerienne.jpg",
      "/images/destinations/cote-azur/villefranche-sur-mer.jpg",
      "/images/destinations/cote-azur/cannes.png",
      "/images/destinations/cote-azur/menton.jpg",
    ],
    center: { lat: 43.53, lng: 7.05 },
  },
  {
    slug: "corse",
    name: "Corse",
    country: "France",
    flag: "FR",
    region: "Méditerranée — Île de Beauté",
    tagline: "L'île sauvage aux mille couleurs",
    description:
      "La Corse s'impose comme l'une des plus belles destinations de voile de Méditerranée. Ses 1 000 km de côtes découpées, ses eaux émeraude et ses criques inaccessibles à pied en font une expérience de navigation unique. Nature préservée classée UNESCO, villages perchés et gastronomie généreuse.",
    boatCount: 224,
    imageSeed: "corse-plage",
    heroSeed: "corse-hero",
    heroImage: "/images/destinations/corse/pexels-slimmars-13-197677686-38525042.jpg",
    bestPeriod: "Mai à Septembre",
    avgTemp: "24°C",
    avgWind: "Force 3-5",
    priceFrom: 250,
    activities: ["Randonnée nautique", "Plongée", "Kayak", "Pêche", "Snorkeling", "Canyoning"],
    highlights: [
      { title: "Golfe de Porto", desc: "Site UNESCO aux falaises de granit rouge plongeant dans une mer turquoise.", icon: "fa-mountain", image: "/images/destinations/corse/golfe-de-porto.jpg" },
      { title: "Réserve de Scandola", desc: "Réserve naturelle protégée, accessible uniquement par la mer.", icon: "fa-leaf", image: "/images/destinations/corse/scandola.jpg" },
      { title: "Bonifacio", desc: "Cité médiévale perchée sur des falaises calcaires blanches à couper le souffle.", icon: "fa-city", image: "/images/destinations/corse/bonifacio.jpg" },
      { title: "Désert des Agriates", desc: "Plages sauvages désertes aux eaux dignes des Caraïbes.", icon: "fa-umbrella-beach", image: "/images/destinations/corse/desert-agriates.jpg" },
    ],
    tags: ["Nature", "Aventure", "Plage", "Culture", "Déconnexion"],
    gallerySeeds: ["corse1", "corse2", "corse3", "corse4"],
    galleryImages: [
      "/images/destinations/corse/pexels-arnaud-38670021.jpg",
      "/images/destinations/corse/pexels-slimmars-13-197677686-38434441.jpg",
      "/images/destinations/corse/pexels-mermoz-lionel-622163994-18035844.jpg",
      "/images/destinations/corse/pexels-arnaud-38669979.jpg",
      "/images/destinations/corse/pexels-slimmars-13-197677686-38525043.jpg",
    ],
    center: { lat: 42.15, lng: 9.05 },
  },
  {
    slug: "cyclades",
    name: "Cyclades",
    country: "Grèce",
    flag: "GR",
    region: "Mer Égée — Grèce",
    tagline: "L'archipel des dieux",
    description:
      "Les Cyclades, c'est la définition de la destination voile parfaite : un vent régulier (le Meltemi), des eaux bleu cobalt, des villages aux maisons blanches et bleues, des tavernes au bord de l'eau et des couchers de soleil légendaires. Santorin, Mykonos, Paros, Naxos… chaque île a sa personnalité.",
    boatCount: 487,
    imageSeed: "greece-island",
    heroSeed: "cyclades-hero",
    heroImage: "/images/destinations/cyclades/pexels-vince-38299672.jpg",
    bestPeriod: "Juin à Septembre",
    avgTemp: "28°C",
    avgWind: "Force 4-6 (Meltemi)",
    priceFrom: 180,
    activities: ["Voile sportive", "Plongée", "Snorkeling", "Randonnée", "Dégustation culinaire", "Visite archéologique"],
    highlights: [
      { title: "Santorin", desc: "Le coucher de soleil à Oia, les falaises volcaniques et les vins locaux.", icon: "fa-sun", image: "/images/destinations/cyclades/santorin.jpg" },
      { title: "Mykonos", desc: "Île festive et cosmopolite, plages légendaires et nuits animées.", icon: "fa-music", image: "/images/destinations/cyclades/mykonos.jpg" },
      { title: "Paros & Antiparos", desc: "Perles méconnues aux plages turquoise et villages authentiques.", icon: "fa-gem", image: "/images/destinations/cyclades/paros.jpg" },
      { title: "Naxos", desc: "La plus grande des Cyclades, mélange de montagne et de mer.", icon: "fa-mountain", image: "/images/destinations/cyclades/naxos.jpg" },
    ],
    tags: ["Voile", "Aventure", "Gastronomie", "Culture", "Plage"],
    gallerySeeds: ["cyclades1", "cyclades2", "cyclades3", "cyclades4"],
    galleryImages: [
      "/images/destinations/cyclades/pexels-benprater-31095031.jpg",
      "/images/destinations/cyclades/pexels-vince-38299672.jpg",
      "/images/destinations/cyclades/pexels-daciana-cristina-visan-2149801141-32153249.jpg",
      "/images/destinations/cyclades/pexels-tommy-elliott-1609542918-28035654.jpg",
      "/images/destinations/cyclades/pexels-diego-f-parra-33199-15241829.jpg",
    ],
    center: { lat: 37.05, lng: 25.35 },
  },
  {
    slug: "baleares",
    name: "Baléares",
    country: "Espagne",
    flag: "ES",
    region: "Méditerranée — Espagne",
    tagline: "L'archipel espagnol du soleil",
    description:
      "Majorque, Minorque, Ibiza et Formentera : les Baléares offrent une diversité saisissante. Des criques sauvages de Formentera aux calanques de Majorque, chaque île a sa propre identité. Navigation facile, vents modérés et ports bien équipés pour tous les niveaux.",
    boatCount: 356,
    imageSeed: "spain-ocean",
    heroSeed: "baleares-hero",
    heroImage: "/images/destinations/baleares/mallorca-cala.jpg",
    bestPeriod: "Mai à Octobre",
    avgTemp: "25°C",
    avgWind: "Force 2-4",
    priceFrom: 220,
    activities: ["Plongée", "Snorkeling", "Jet-ski", "Stand-up paddle", "Pêche", "Randonnée"],
    highlights: [
      { title: "Formentera", desc: "Eaux les plus claires de Méditerranée, ambiance bohème et décontractée.", icon: "fa-water" },
      { title: "Sa Calobra (Majorque)", desc: "Crique mythique accessible uniquement par la mer, falaises vertigineuses.", icon: "fa-mountain" },
      { title: "Ibiza & Ses Salines", desc: "Réserve naturelle classée UNESCO entourant les plages iconiques.", icon: "fa-leaf" },
      { title: "Minorque", desc: "La moins connue et la plus sauvage des Baléares.", icon: "fa-compass" },
    ],
    tags: ["Famille", "Plage", "Fête", "Nature", "Voile"],
    gallerySeeds: ["baleares1", "baleares2", "baleares3", "baleares4"],
    center: { lat: 39.35, lng: 2.75 },
  },
  {
    slug: "dalmatie",
    name: "Côte Dalmate",
    country: "Croatie",
    flag: "HR",
    region: "Mer Adriatique — Croatie",
    tagline: "Mille îles, mille aventures",
    description:
      "Avec ses 1 200 îles, îlots et récifs, la côte dalmate est le paradis du skipper. Eaux parmi les plus propres d'Europe, archipel infini, villes médiévales classées UNESCO et gastronomie croate généreuse. Dubrovnik, Split, les Kornati… une navigation sans fin.",
    boatCount: 623,
    imageSeed: "mediterr-sea",
    heroSeed: "dalmatia-hero",
    heroImage: "/images/destinations/cote dalmate/pexels-fede-roveda-1461538-4234629.jpg",
    bestPeriod: "Juin à Septembre",
    avgTemp: "27°C",
    avgWind: "Force 3-5 (Bora & Jugo)",
    priceFrom: 160,
    activities: ["Kayak de mer", "Plongée", "Snorkeling", "Visite culturelle", "Randonnée", "Pêche"],
    highlights: [
      { title: "Parc nat. de Kornati", desc: "89 îles inhabitées parmi les plus beaux archipels de Méditerranée.", icon: "fa-compass" },
      { title: "Dubrovnik", desc: "La « Perle de l'Adriatique », remparts médiévaux et vieille ville magique.", icon: "fa-city" },
      { title: "Hvar & Brač", desc: "Les îles les plus ensoleillées de Croatie, plages et vignes en terrasse.", icon: "fa-sun" },
      { title: "Split & Parc Krka", desc: "La ville romaine de Dioclétien et les cascades spectaculaires.", icon: "fa-water" },
    ],
    tags: ["Culture", "Nature", "Aventure", "Gastronomie", "Voile"],
    gallerySeeds: ["dalmatia1", "dalmatia2", "dalmatia3", "dalmatia4"],
    galleryImages: [
      "/images/destinations/cote dalmate/pexels-135445684-37836432.jpg",
      "/images/destinations/cote dalmate/pexels-vince-2265876.jpg",
      "/images/destinations/cote dalmate/pexels-olliecraig1-5102874.jpg",
      "/images/destinations/cote dalmate/pexels-ivan-drazic-20457695-13737471.jpg",
      "/images/destinations/cote dalmate/pexels-james-bond-756164766-31884809.jpg",
    ],
    center: { lat: 43.65, lng: 15.95 },
  },
  {
    slug: "bretagne",
    name: "Bretagne",
    country: "France",
    flag: "FR",
    region: "Atlantique — France",
    tagline: "La mer à l'état brut",
    description:
      "La Bretagne offre une expérience de navigation radicalement différente : côtes découpées, phares légendaires, marées spectaculaires, ambiance sauvage et gastronomie de caractère. Pour les navigateurs qui cherchent l'aventure et l'authenticité plutôt que le soleil méditerranéen.",
    boatCount: 178,
    imageSeed: "bretagne-mer",
    heroSeed: "bretagne-hero",
    heroImage: "/images/destinations/bretagne/pexels-ishaq-ali-anis-2149874681-31207526.jpg",
    bestPeriod: "Juin à Août",
    avgTemp: "18°C",
    avgWind: "Force 4-6",
    priceFrom: 130,
    activities: ["Voile sportive", "Surf", "Pêche", "Randonnée côtière", "Observation de cétacés", "Planche à voile"],
    highlights: [
      { title: "Golfe du Morbihan", desc: "Mer intérieure mystérieuse aux 40 îles, marées et courants fascinants.", icon: "fa-water", image: "/images/destinations/bretagne/pexels-jan-van-der-wolf-11680885-20182858.jpg" },
      { title: "Archipel des Glénan", desc: "Lagon aux eaux turquoise inattendu, bijou caché de l'Atlantique.", icon: "fa-gem", image: "/images/destinations/bretagne/pexels-gilles-33538200.jpg" },
      { title: "Belle-Île-en-Mer", desc: "La plus grande île bretonne, côte sauvage et village de Locmaria.", icon: "fa-umbrella-beach", image: "/images/destinations/bretagne/pexels-philippe-serrand-337910945-17891904.jpg" },
      { title: "Pointe du Raz", desc: "L'un des caps les plus spectaculaires d'Europe, face à l'Atlantique.", icon: "fa-wind", image: "/images/destinations/bretagne/pexels-gilles-33552107.jpg" },
    ],
    tags: ["Aventure", "Nature", "Voile sportive", "Authenticité", "Gastronomie"],
    gallerySeeds: ["bretagne1", "bretagne2", "bretagne3", "bretagne4"],
    galleryImages: [
      "/images/destinations/bretagne/pexels-jan-van-der-wolf-11680885-20182858.jpg",
      "/images/destinations/bretagne/pexels-gilles-33538200.jpg",
      "/images/destinations/bretagne/pexels-philippe-serrand-337910945-17891904.jpg",
      "/images/destinations/bretagne/pexels-slimmars-13-197677686-34681436.jpg",
      "/images/destinations/bretagne/pexels-philippe-serrand-337910945-18382376.jpg",
    ],
    center: { lat: 47.6, lng: -3.0 },
  },
];
