import type { FullDestination } from "@/shared/types";

export const ALL_DESTINATIONS: FullDestination[] = [
  {
    slug: "cote-azur",
    name: "Côte d'Azur",
    country: "France",
    flag: "FR",
    region: "Méditerranée française",
    tagline: "Le joyau bleu de la Méditerranée",
    description:
      "De Nice à Menton en passant par Cannes et Monaco, la Côte d'Azur est l'une des destinations de voile les plus réputées au monde. Ses eaux cristallines, ses criques secrètes et ses ports de prestige en font un terrain de jeu idéal pour tous les plaisanciers.",
    boatCount: 312,
    imageSeed: "cote-azur",
    heroSeed: "azur-hero",
    bestPeriod: "Juin à Septembre",
    avgTemp: "26°C",
    avgWind: "Force 3-4",
    priceFrom: 290,
    activities: ["Snorkeling", "Plongée", "Water-ski", "Pêche", "Wakeboard", "Paddle", "Jet-ski"],
    highlights: [
      { title: "Calanques de Cassis", desc: "Fjords méditerranéens aux eaux turquoise, accessibles uniquement par la mer.", icon: "fa-water", image: "/images/destinations/cote-azur/calanques-cassis.jpg" },
      { title: "Îles de Lérins", desc: "Deux îles préservées face à Cannes, paradis de biodiversité marine.", icon: "fa-umbrella-beach", image: "/images/destinations/cote-azur/iles-de-lerins.jpg" },
      { title: "Monaco & Menton", desc: "Naviguez entre glamour et charme provençal le long de la frontière italienne.", icon: "fa-crown", image: "/images/destinations/cote-azur/monaco.jpg" },
      { title: "Saint-Tropez", desc: "Le mythe de la Riviera, entre vieilles pierres et yachts de rêve.", icon: "fa-star", image: "/images/destinations/cote-azur/saint-tropez.jpg" },
    ],
    tags: ["Luxe", "Famille", "Plage", "Culture", "Gastronomie"],
    gallerySeeds: ["azur1", "azur2", "azur3", "azur4"],
    galleryImages: [
      "/images/destinations/cote-azur/nice-aerienne.jpg",
      "/images/destinations/cote-azur/villefranche-sur-mer.jpg",
      "/images/destinations/cote-azur/cannes.png",
      "/images/destinations/cote-azur/menton.jpg",
    ],
    center: { lat: 43.53, lng: 7.05 },
  },
  {
    slug: "corse",
    name: "Corse",
    country: "France",
    flag: "FR",
    region: "Méditerranée — Île de Beauté",
    tagline: "L'île sauvage aux mille couleurs",
    description:
      "La Corse s'impose comme l'une des plus belles destinations de voile de Méditerranée. Ses 1 000 km de côtes découpées, ses eaux émeraude et ses criques inaccessibles à pied en font une expérience de navigation unique. Nature préservée classée UNESCO, villages perchés et gastronomie généreuse.",
    boatCount: 224,
    imageSeed: "corse-plage",
    heroSeed: "corse-hero",
    heroImage: "/images/destinations/corse/pexels-slimmars-13-197677686-38525042.jpg",
    bestPeriod: "Mai à Septembre",
    avgTemp: "24°C",
    avgWind: "Force 3-5",
    priceFrom: 250,
    activities: ["Randonnée nautique", "Plongée", "Kayak", "Pêche", "Snorkeling", "Canyoning"],
    highlights: [
      { title: "Golfe de Porto", desc: "Site UNESCO aux falaises de granit rouge plongeant dans une mer turquoise.", icon: "fa-mountain", image: "/images/destinations/corse/golfe-de-porto.jpg" },
      { title: "Réserve de Scandola", desc: "Réserve naturelle protégée, accessible uniquement par la mer.", icon: "fa-leaf", image: "/images/destinations/corse/scandola.jpg" },
      { title: "Bonifacio", desc: "Cité médiévale perchée sur des falaises calcaires blanches à couper le souffle.", icon: "fa-city", image: "/images/destinations/corse/bonifacio.jpg" },
      { title: "Désert des Agriates", desc: "Plages sauvages désertes aux eaux dignes des Caraïbes.", icon: "fa-umbrella-beach", image: "/images/destinations/corse/desert-agriates.jpg" },
    ],
    tags: ["Nature", "Aventure", "Plage", "Culture", "Déconnexion"],
    gallerySeeds: ["corse1", "corse2", "corse3", "corse4"],
    galleryImages: [
      "/images/destinations/corse/pexels-arnaud-38670021.jpg",
      "/images/destinations/corse/pexels-slimmars-13-197677686-38434441.jpg",
      "/images/destinations/corse/pexels-mermoz-lionel-622163994-18035844.jpg",
      "/images/destinations/corse/pexels-arnaud-38669979.jpg",
      "/images/destinations/corse/pexels-slimmars-13-197677686-38525043.jpg",
    ],
    center: { lat: 42.15, lng: 9.05 },
  },
  {
    slug: "bretagne",
    name: "Bretagne",
    country: "France",
    flag: "FR",
    region: "Atlantique — France",
    tagline: "La mer à l'état brut",
    description:
      "La Bretagne offre une expérience de navigation radicalement différente : côtes découpées, phares légendaires, marées spectaculaires, ambiance sauvage et gastronomie de caractère. Pour les navigateurs qui cherchent l'aventure et l'authenticité plutôt que le soleil méditerranéen.",
    boatCount: 178,
    imageSeed: "bretagne-mer",
    heroSeed: "bretagne-hero",
    heroImage: "/images/destinations/bretagne/pexels-ishaq-ali-anis-2149874681-31207526.jpg",
    bestPeriod: "Juin à Août",
    avgTemp: "18°C",
    avgWind: "Force 4-6",
    priceFrom: 130,
    activities: ["Voile sportive", "Surf", "Pêche", "Randonnée côtière", "Observation de cétacés", "Planche à voile"],
    highlights: [
      { title: "Golfe du Morbihan", desc: "Mer intérieure mystérieuse aux 40 îles, marées et courants fascinants.", icon: "fa-water", image: "/images/destinations/bretagne/pexels-jan-van-der-wolf-11680885-20182858.jpg" },
      { title: "Archipel des Glénan", desc: "Lagon aux eaux turquoise inattendu, bijou caché de l'Atlantique.", icon: "fa-gem", image: "/images/destinations/bretagne/pexels-gilles-33538200.jpg" },
      { title: "Belle-Île-en-Mer", desc: "La plus grande île bretonne, côte sauvage et village de Locmaria.", icon: "fa-umbrella-beach", image: "/images/destinations/bretagne/pexels-philippe-serrand-337910945-17891904.jpg" },
      { title: "Pointe du Raz", desc: "L'un des caps les plus spectaculaires d'Europe, face à l'Atlantique.", icon: "fa-wind", image: "/images/destinations/bretagne/pexels-gilles-33552107.jpg" },
    ],
    tags: ["Aventure", "Nature", "Voile sportive", "Authenticité", "Gastronomie"],
    gallerySeeds: ["bretagne1", "bretagne2", "bretagne3", "bretagne4"],
    galleryImages: [
      "/images/destinations/bretagne/pexels-jan-van-der-wolf-11680885-20182858.jpg",
      "/images/destinations/bretagne/pexels-gilles-33538200.jpg",
      "/images/destinations/bretagne/pexels-philippe-serrand-337910945-17891904.jpg",
      "/images/destinations/bretagne/pexels-slimmars-13-197677686-34681436.jpg",
      "/images/destinations/bretagne/pexels-philippe-serrand-337910945-18382376.jpg",
    ],
    center: { lat: 47.6, lng: -3.0 },
  },
];
